name: PR → beta.mp3
on:
  pull_request:
    branches: [ main ]

jobs:
  build-beta:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install boto3

      - name: Run Polly synth → beta
        env:
          AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION:            ${{ secrets.AWS_REGION }}
          S3_BUCKET:             ${{ secrets.S3_BUCKET }}
          S3_KEY: polly-audio/beta.mp3
          TEXT_FILE: speech.txt
          VOICE_ID: Joanna
        run: python synthesize.py